---
title: "Week 7 Practice 2"
author: "Yu-Wen Pu"
date: "2018-04-10"
output: github_document
---

```{r}
knitr::opts_chunk$set(results = "hold", fig.retina = 2)
set.seed(1830)
```

## 讀入資料，並指定資料型別

```{r}
survey <- read.table("2018class.csv", header = TRUE, sep = ",", colClasses = c(
    "numeric", "integer", "factor", "numeric", "numeric",
    "numeric", "integer", "factor", "integer", "integer"))
head(survey)
str(survey)
```

## Encode Vector as Factor (Category, Enum)

```{r}
survey$gender <- factor(survey$gender,
    levels = c(1, 2), labels = c("female", "male"))
str(survey$gender)
table(survey$gender)
survey$smoke <- factor(survey$smoke, ordered = TRUE,
    levels = c(1, 2), labels = c("no", "yes"))
str(survey$smoke)
table(survey$smoke)
head(survey)
```

## 畫直方圖、常態分佈曲線、最接近實際值的曲線 - height

```{r a}
hist(survey$height, breaks = 35, xlim = c(min(survey$heigh), max(survey$heigh)),
     xlab = "Height", main = "", xaxt = "n", yaxt = "n")
axis(side = 1, at = seq(from = min(survey$heigh), to = max(survey$heigh), by = 5),
     pos = 0, las = 0)
axis(side = 2, pos = min(survey$heigh), las = 2)
par(new = TRUE)  # 疊加圖形
x <- seq(from = min(survey$heigh), to = max(survey$heigh), by = .01)
plot(x, dnorm(x, mean = mean(survey$heigh), sd = sd(survey$heigh)),
     type = "l", col = "red", xlim = c(min(survey$heigh), max(survey$heigh)),
     xlab = "", ylab = "", xaxt = "n", yaxt = "n", bty = "n")  # bty = "n": no border
  # lines() 會疊加在既有圖形上
lines(density(survey$heigh), col = "blue")  # kernel density estimation
```

## 畫直方圖、常態分佈曲線、最接近實際值的曲線 - random

```{r b}
hist(survey$random, breaks = 35, xlim = c(min(survey$random), max(survey$random)),
     xlab = "Random Number", main = "", xaxt = "n", yaxt = "n")
axis(side = 1, at = seq(from = min(survey$random), to = max(survey$random), by = 500),
     pos = 0, las = 0)
axis(side = 2, pos = min(survey$random), las = 2)
par(new = TRUE)  # 疊加圖形
x <- seq(from = min(survey$random), to = max(survey$random), by = .1)
plot(x, dnorm(x, mean = mean(survey$random), sd = sd(survey$random)),
     type = "l", col = "red", xlim = c(min(survey$random), max(survey$random)),
     xlab = "", ylab = "", xaxt = "n", yaxt = "n", bty = "n")  # bty = "n": no border
  # lines() 會疊加在既有圖形上
lines(density(survey$random), col = "blue")  # kernel density estimation
```
