---
title: "Week 4 Practice 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1830)
```

## Central Tendency

```{r}
nums <- sample(30:60, 24, replace=TRUE)
cat(nums)
```

```{r}
summary(nums)
```

```{r}
m <- mean(nums)
m.trim <- mean(nums, trim = .1)
med <- median(nums)
cat(m, m.trim, med)
```

```{r nums_hist}
hist(nums, main = "Title Goes Here", breaks = 20, col = "red")
```

```{r}
library(psych)
describe(nums)
```

## Data Types

### scalar

```{r}
scalar_var1 <- 6
scalar_var2 <- "STRING"
scalar_var3 <- TRUE
```

### vector

```{r}
vector_var1 <- c(1, 3, 5, 7, 9)  # 限同型別
vector_var2 <- c("apple", "boy", "cat", "dog", 'egg', 'fox', 'girl')
vector_var3 <- c(61:70)  # 字串可用雙引號或單引號
vector_var1[3]  # 索引值從 1 開始
vector_var2[c(2, 4, 6)]
vector_var3[7:10]  # 包含頭尾
vector_var3[c(7:10)]
vector_var3[11]  # 不存在，NA
```

### vector (advanced)

```{r}
vector_var4 <- c(1, 3, 5, 7, 9, "a", "b", "c")
vector_var1[5]
typeof(vector_var1)
vector_var4[5]
typeof(vector_var4)
```

### matrix

```{r}
matrix_var1 <- matrix(1:20, nrow = 5, ncol = 4, byrow = FALSE)  # 直列優先
matrix_var2 <- matrix(1:20, nrow = 5, ncol = 4, byrow = TRUE)  # 橫行優先
matrix_var1[2, ]
matrix_var2[2, ]
matrix_var1[, 2]
matrix_var2[, 2]
matrix_var1[3, 4]
matrix_var2[4, c(1:3)]
```

### array

```{r}
dim1 <- c("A1", "A2")
dim2 <- c("B1", "B2", "B3")
dim3 <- c("C1", "C2", "C3", "C4")
array_var1 <- array(1:24, c(2, 3, 4), dimnames = list(dim1, dim2, dim3))
array_var1
```

## Draw Boxplot

### read common data

```{r}
hospital_len <- read.table("Tab5-2.dat", header = TRUE, na.strings = c("999"))
names(hospital_len)
dim(hospital_len)
str(hospital_len)
head(hospital_len)
table(is.na(hospital_len))
```

### read sav data

```{r}
if(!require(haven)) install.packages("haven", repos = "https://cran.r-project.org")
library(haven)
corrects <- read_sav("Fig3-2.sav")
str(corrects)
tail(corrects)
is.integer(corrects$intrus)
as.integer(corrects$intrus)
mean(corrects$intrus)
median(corrects$intrus)
```

### draw stem-and-leaf plot

```{r}
library(aplpack)
stem.leaf(hospital_len$length, Min = 1, Max = 10, m = 1)
```

### draw boxplot

```{r}
boxplot(hospital_len$length)
```

### draw boxplot (advanced)

```{r}
mental_rotation <- read.table("../week3a/Tab3-1.dat", header = TRUE)
head(mental_rotation)
mental_rotation$Accuracy <- factor(mental_rotation$Accuracy, ordered = TRUE,
                                   levels = c(0, 1), labels = c("wrong", "correct"))
                                   # 有順序性，0 代表 wrong，1 代表 correct
head(mental_rotation)
boxplot(mental_rotation$RTsec)
boxplot(mental_rotation$RTsec ~ mental_rotation$Accuracy,
        ylab = "reaction time", col = c("green", "yellow"))
```
