---
title: "Week 11 Practice 2"
author: "Yu-Wen Pu"
date: "2018-05-08"
output: github_document
---

## Correlation

```{r}
knitr::opts_chunk$set(results = "hold", fig.retina = 2)
set.seed(1830)
```

### part 1

```{r}
x <- read.table("Fig9-1.dat", header = TRUE, sep = "")
dim(x)
str(x)
head(x)
```

```{r a}
plot(x$Doctors, x$Infmort, xlab = "physicians per 10000 population",
     ylab = "infant mortality", pch = 19)
abline(lm(x$Infmort ~ x$Doctors), col = "red")
```

### part 2

```{r b}
library(ggplot2)
scatter <- ggplot(x, aes(x = Doctors, y = Infmort))
scatter + geom_point() + geom_smooth(method = "lm") +
    labs(x = "physicians per 10000 population", y = "infant mortality")
```

```{r c}
scatter + geom_point() + geom_smooth(method = "lm", color = "red", se = FALSE) +
    labs(x = "physicians per 10000 population", y = "infant mortality")
```

```{r d}
scatter + geom_point() + 
    geom_smooth(method = "lm", color = "red", alpha = .2, fill = "green") +
    labs(x = "physicians per 10000 population", y = "infant mortality")
```

### part 3

```{r}
x <- read.table("Fig9-5.dat", header = TRUE, sep = "")
head(x, n = 3)
cor(x$Pace, x$Heart)
cor.test(x$Pace, x$Heart)
```

### part 4

```{r}
library(haven)
x <- read_sav("tcs04.sav")
dim(x)
```

```{r}
gender <- table(x$gender)
gender
chisq.test(gender)
```

```{r}
table(x$P5)
table(is.na(x$P5))
```
