---
title: "Week 8 Exercise"
author: "Yu-Wen Pu"
date: "2018-04-17"
output: html_document
---

```{r}
knitr::opts_chunk$set(results = "hold", fig.retina = 2)
set.seed(1830)
```

## Sampling Error

```{r}
draw <- function(n_samples) {
    pop_mean = 165.35
    pop_sd = 8.37
    sample_size = 15
    xbar <- numeric(length = n_samples)
    for (i in 1:n_samples) {
        x <- rnorm(n = sample_size, mean = pop_mean, sd = pop_sd)
        xbar[i] <- mean(x)
    }
    spl_mean <- round(mean(xbar), digits = 2)
    spl_sd <- round(sd(xbar), digits = 2)
    upper_limit <- ceiling(max(xbar))
    lower_limit <- floor(min(xbar))
    hist(xbar, breaks = seq(from = lower_limit, to = upper_limit, by = 1),
         xlab = "Mean of Sample", main = "", xaxt = "n", yaxt = "n", col = "red")
    axis(side = 1, at = seq(from = lower_limit, to = upper_limit, by = 5),
         pos = 0, las = 0)
    axis(side = 2, pos = lower_limit, las = 2)
    legend("topright", paste("mean = ", spl_mean, "\nstderr = ", spl_sd,
           "\n# of samples = ", n_samples, "\n"), bty = "n", cex = 1)
}
```

```{r a}
par(mfrow = c(1, 3), mar = c(5, 4, 5, 4))
draw(10)
draw(100)
draw(10000)
```
