---
title: "Week 12 Practice 1"
author: "Yu-Wen Pu"
date: "2018-05-21"
output: github_document
---

## regression

```{r}
knitr::opts_chunk$set(results = "hold", fig.retina = 2)
set.seed(1830)
```

### part 1

```{r}
d <- read.table("Tab10-1.dat", header = TRUE, sep = "")
library(aplpack)
```

```{r a}
stem.leaf(d$Stress)
boxplot(d$Stress, horizontal = TRUE, main = "stress")
```

```{r b}
stem.leaf(d$Symptoms)
boxplot(d$Symptoms, horizontal = TRUE, main = "symptoms")
```

### part 2

```{r}
cor.test(d$Stress, d$Symptoms, alternative = "two.sided")
```

### part 3

```{r}
(regress <- lm(d$Symptoms ~ d$Stress))
cat(strrep("#", 32), fill = TRUE)
summary(regress)
cat(strrep("#", 32), fill = TRUE)
str(regress)
```

```{r c}
plot(d$Stress, d$Symptoms, xlim = c(0, 80), ylim = c(50, 200),
     main = "symptoms as a function of stress",
     xlab = "stress", ylab = "symptoms",
     pch = 19, bty = "n")
abline(lm(d$Symptoms ~ d$Stress), col = "red")
b <- round(regress$coefficients[["d$Stress"]], digits = 2)
a <- round(regress$coefficients[["(Intercept)"]], digits = 2)
legend(35, 175, substitute(
        paste(hat(Y), " = ", b, " * X + ", a),
        list(b = b, a = a)
    ), bty = "n")
```
