---
title: "Week 9 Practice 1"
author: "Yu-Wen Pu"
date: "2018-04-24"
output: github_document
---

```{r}
knitr::opts_chunk$set(results = "hold", fig.retina = 2)
set.seed(1830)
```

## 語法說明

```{r eval=FALSE}
# both are the same
dataset <- edit(dataset)
fix(dataset)
```

```{r eval=FALSE}
apply(x, margin, fun)
# x: data object
# margin: 1 for rows, 2 for columns
# fun: apply this function to data object
```

## 模擬樣本分佈

```{r}
survey <- read.table("../week7/2018class.csv", header = TRUE, sep = ",")
x <- survey$height
length(x)
mean(x)
sd(x)
head(x)
```

```{r}
y <- data.frame(p1 = numeric(0), p2 = numeric(0), p3 = numeric(0),
                p4 = numeric(0), p5 = numeric(0), mean = numeric(0),
                sd = numeric(0), low_critical_val = numeric(0),
                high_critical_val = numeric(0), p_val = numeric(0))
y <- edit(y)
y
```

```{r}
n_samples <- nrow(y)  # number of rows
for (i in 1:n_samples) {
    print(i)
    y$mean[i] <- apply(y[i, c(1:5)], 1, mean)
    y$sd[i] <- apply(y[i, c(1:5)], 1, sd)
    y$low_critical_val[i] <- y$mean[i] - 1.96 * y$sd[i]
    y$high_critical_val[i] <- y$mean[i] + 1.96 * y$sd[i]
    if (y$mean[i] > mean(x)) {
        y$p_val[i] <- format(round(pnorm(y$mean[i], mean = mean(x),
                                         sd = sd(x), lower.tail = FALSE),
                                   digits = 3),
                             nsmall = 3)  # minimum number of digits
    } else {
        y$p_val[i] <- format(round(pnorm(y$mean[i], mean = mean(x),
                                         sd = sd(x), lower.tail = TRUE),
                                   digits = 3),
                             nsmall = 3)
    }
}
```

```{r}
y
write.csv(y, file = "height.csv", row.names = FALSE)  # output to csv
```










