---
title: "Exercise 2"
author: "0316213 Yu-Wen Pu"
output:
  pdf_document:
    includes:
      in_header: header.tex
    keep_tex: yes
    latex_engine: xelatex
  html_document:
    df_print: paged
---

##### 3.1 (a)

```{r}
scores <- c(54, 52, 51, 50, 36, 55, 44, 46, 57, 44, 43, 52, 38, 46,
            55, 34, 44, 39, 43, 36, 55, 57, 36, 46, 49, 46, 49, 47)
```

```{r}
hist(scores)
```

##### 3.1 (b)

類似倒 U 字型。

##### 3.2

```{r}
stem(scores, scale = .5)
```

##### 3.4

```{r}
summary(scores)
```

有，平均分數是 46.57 分，高於 20 分。

##### 3.5 (a)

有，在 Passage 組有很多人 70 分以上，在 NoPassage 組則沒有人超過 70 分。

##### 3.5 (b)

```{r}
new_scores <- c(66, 75, 72, 71, 55, 56, 72, 93, 73, 72, 72, 73, 91, 66, 71, 56, 59)
```

```{r}
library(aplpack)
stem.leaf.backback(new_scores, scores)
```

##### 3.5 (c)

有看文章段落的人的分數明顯比沒看的人來得高。

##### 3.22 & 3.23

```{r}
total_households <- c(52799, 63401, 71120, 80776, 86789, 89479, 91066, 92830, 92347)
women_households <- c(4507, 5591, 7242, 8705, 10129, 10445, 10608, 10890, 10890)
family_size <- c(3.33, 3.14, 2.94, 2.76, 2.69, 2.66, 2.64, 2.62, 2.63)
year <- c(1960, 1970, 1975, 1980, 1985, 1987, 1988, 1989, 1990)
```

```{r}
plot(total_households ~ year, type = "l", ylim = c(0, 100000),
     ylab = "Total Households", col = "red", lwd = 3)
par(new = TRUE)
plot(women_households ~ year, type = "l", ylim = c(0, 100000),
     ylab = "", col = "blue", lwd = 3, axes = FALSE)
mtext("Women Households", side = 4, col = "blue")
axis(side = 4, ylim = c(0, 100000), col = "blue", col.axis = "blue")
```

```{r}
plot(family_size ~ year, type = "l", ylim = c(2, 4),
     ylab = "Family Size", col = "red", lwd = 3)
```

1. 女性領導的家庭增加的幅度不如家庭總數增加的幅度。也就是說，雖然家庭的數量增加了，但多數家庭仍是由非女性（通常是男性）領導。
2. 家庭大小有朝向小家庭發展的趨勢。
